### ISSUE TITLE
symbol not found in flat namespace '_fftw_destroy_plan'

### ISSUE THREAD

**Issue by md-arif-shaikh** [moble/spinsfast#11]
I face recurring issues when installing `spinsfast` in GitHub actions on MacOS. Earlier, I followed the instruction to use homebrew for `FFTW` and that issue was fixed. But now I am facing another similar issue

`E   ImportError: dlopen(/Users/runner/miniconda3/envs/test/lib/python3.9/site-packages/spinsfast/cextension.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_fftw_destroy_plan'`

Here are relevant steps I am using to install `spinfast` https://github.com/vijayvarma392/gw_eccentricity/blob/main/.github/workflows/test.yml#L41

Do you have any idea how to fix this?

**Comment by moble** [comment]
Sorry to hear you're having trouble.  I've never run into this sort of issue.  I wonder if it's because you're mixing conda and pip.  (I do this all the time on my own Mac, but never tried it in github actions.)  Looking at the [two](https://github.com/moble/spinsfast/blob/7ea0b81fcccd0c237373da50ab0cf8cf954dd399/.github/workflows/build.yml#L15) [places](https://github.com/moble/scri/blob/544f481b65a00d08271d2faa53908df64e054fc6/.github/workflows/build.yml#L49C15-L49C38) where my own workflows use this package, I always install python using [actions/setup-python](https://github.com/actions/setup-python), and then use pip-based tools to install spinsfast.  That might be worth a try.

**Comment by md-arif-shaikh** [comment]
Thanks a lot! it just worked. Using `actions/setup-python@v5` fixed it.

**Comment by moble** [comment]
Glad to hear it.  Let me know if you have any other issues.
