### ISSUE TITLE
`map2salm` fails for certain numpy.array views

### ISSUE THREAD

**Issue by lzkelley** [moble/spinsfast#3]
I have an `numpy.ndarray` called `data` with 3 dimensions of sizes: `[N, M, L]`, and an appropriately chosen `LMAX`.  If I do transformations with slices along the first axis, everything works fine, i.e. 

Success:
```
spinsfast.map2salm(data[0, :, :], 1, LMAX)
```

If the array is reshaped (e.g. via `numpy.moveaxis`) to be `[M, L, N]` and I take slices along the last axis, the results are erroneous, i.e.

Failure:
```
spinsfast.map2salm(data[:, :, 0], 1, LMAX)
```

I realized (after a *long*) time that it could be a contiguous data issue, and indeed I was able to fix the problem by doing,

Success:
```
spinsfast.map2salm(np.copy(data[:, :, 0]), 1, LMAX)
```

I'm using the anaconda version (v104.1) which doesn't seem to have the wrapper functions you recently added.  I see that you also added a `np.ascontiguousarray` call; is that to fix this same issue?  If not, it shouldn't be hard for me to create a MWE if that's helpful.

**Comment by moble** [comment]
>  I see that you also added a np.ascontiguousarray call; is that to fix this same issue? 

Precisely.  This is fundamentally a pretty simple C code, which just takes a pointer to the first element of an array, and assumes consecutive elements are just one `double` along from that in memory.  In principle, the C code could be rewritten to take a "stride", which would solve the problem without needing to copy any data.  But this way works for me.

> I'm using the anaconda version (v104.1) which doesn't seem to have the wrapper functions you recently added.

The newer version with the wrappers is [available on conda](https://anaconda.org/moble/spinsfast/files).  It's possible that a simple `conda update` would have too many dependencies on other old things you have, which would mean conda isn't selecting the newest version of `spinsfast` because it wants to keep an old `numpy`, for example.  Alternatively, "manual" installation is trivial, even within a conda environment.  Just download the code and run `python python/setup.py install` from the top directory.

(Note that that version number is just whatever [the original `spinsfast` code](http://astrophysics.physics.fsu.edu/~huffenbe/research/spinsfast/index.html) used.  I haven't changed it, because they still own the package, so different conda version will still report the same package version.)
