### ISSUE TITLE
Error linking fftw against glibc2.15

### ISSUE THREAD

**Issue by lzkelley** [moble/spinsfast#4]
I'm trying to get the package to work on a cluster (_read: I have no root access_), and there are issues with the fftw package.

The conda install works fine with `conda install --channel https://conda.anaconda.org/moble spinsfast` (though, for some reason, `conda install --channel moble spinsfast` failed).  But when I try to import, I get:

```
(py35)[lkelley@holy2a24208 scripts]$ python -c "import spinsfast"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/n/home00/lkelley/.conda/envs/py35/lib/python3.6/site-packages/spinsfast/__init__.py", line 17, in <module>
    from .spinsfast_module import *
ImportError: /lib64/libm.so.6: version `GLIBC_2.15' not found (required by /n/home00/lkelley/.conda/envs/py35/lib/python3.6/site-packages/spinsfast/../../../libfftw3.so.3)
```

I'm not sure if this is an issue with the build _linking_ against the wrong glibc version, or if it _requires_ 2.15 and that's not installed.  The system has GNU libc 2.12 installed (says `ldd --version`).

**Comment by lzkelley** [comment]
**Manual compilation** solved the problem.  I guess our system is just hella old, and this libc version wasn't built against in any of the conda installations.  (_Aside_: README says to run `python python/setup.py install` but the `setup.py` script was moved to the root directory).

**Comment by moble** [comment]
Coincidentally, my most recent commits have been to set up "manylinux1" wheels that deal with similar issues.  The idea is to do something like what conda does, but through pip only.  But [the specification](https://www.python.org/dev/peps/pep-0513/) calls for things to be built on CentOS 5.11, precisely because it is so old that any reasonably new system would be able to run things built on it.  In particular, it only has up to `GLIBC_2.5`, which you presumably also have.  I guess the Travis-CI container that I have conda building on is just too new.

So you could try doing `pip install spinsfast` right inside your conda env, to get these newer (but older-compatible) builds.  But — assuming I can get it running — my next commits will involve building the conda versions on that same CentOS 5.11 container, which would also solve such problems.

> (Aside: README says to run python python/setup.py install but the setup.py script was moved to the root directory).

Thanks for pointing that out.  Fixed now.

**Comment by moble** [comment]
Okay, turns out conda dropped support for CentOS 5 a while ago, so I'd have to build with an older version of conda to support that, which seems excessive.  Anyway, the `pip` route seems to work with such old versions.  And I've checked that the latest build on anaconda does work with CentOS 6 — which only has glibc 2.12.  (I had to rebuild the fftw package, too.)
